version: '3.7'

services:
  mysql:
    image: mysql:8.0
    environment: 
      - MYSQL_ROOT_PASSWORD=boot
      - MYSQL_HOST=127.0.0.1
    ports: 
      - 3306:3306

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "cargo run"
    links:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:boot@mysql/items
    ports:
      - 6666:6666

  frontend:
    tty: true
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: "tarot_frontend"
    command: "yarn start"
    volumes:
      - ./frontend:/home/app/frontend/
      - /home/app/frontend/node_modules
    ports:
      - 3000:3000
    deploy:
      restart_policy:
        condition: on-failure

  


