version: '3.7'

services:
  # redis:
  #   image: "redis:alpine"
  #   ports: 
  #     - "8001:8001"
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  frontend:
    tty: true
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
      # TAROT_APP_FRONTEND_HOST_NAME: localhost:3000
    container_name: "tarot_frontend"
    command: "yarn start"
    volumes:
      # - ./frontend:/home/app/frontend/
      - ./frontend:/home/app/frontend/
      # - ./frontend:/home/aaron/Documents/Development/Tarot/frontend/
      # - /home/app/frontend/node_modulesea
      - /home/app/frontend/node_modules
    ports:
      - 3000:3000
    deploy:
      restart_policy:
        condition: on-failure


